const Cards = {
  Mozi: [
    "Suppose you learned your father just stole a piece of bread from the bakery. What would you do? Would you report him?",
    "Mozi believes that elaborate funeral rituals are unnecessary. What do you think of this claim? (Chapter 25) ",
    "You’re on the battlefield, and your general is describing his plan of attack. You notice a glaring mistake in his plan. What would you do? ",
    "Would you characterize yourself as more likely to obey your superiors or to rebel against them? ",
    "Mozi believes that musical performances are unnecessary. Have you ever played a musical instrument? Do you agree or disagree with Mozi’s claim? (Chapter 32)",
    "Think of a big decision that you made or are about to make. What are the costs and benefits? Were more people hurt or helped from your decision?",
    "Think of someone you love. How many innocent strangers would you kill to save your loved one from immediate death? Impartial caring? (Chapter 16)",
    "What do you think is more effective, reward or punishment? What are some of the goals and fears in life that motivate you?",
    "Describe a time when your superiors rewarded you for an accomplishment. How did that make you feel?",
    "Mozi believes that there are ghosts and spirits that punish humans for bad behavior and reward them for good behavior. Do you believe in karma? Do you believe in the ghosts and spirits that Mozi describes? (Chapter 26)",
    "Suppose you witnessed a smaller, weaker child being bullied by an older, stronger child. How would you react? ",
    "Do you believe that thinking people act accordingly when presented with superior arguments? Why or why not?",
    "Do you believe in ghosts and spirits?",
  ],
  Kongzi: [
    "Suppose you and your partner switched places. What do you think of each other?",
    "Think of the last time you were upset at someone. Now put yourself in the shoes of the other person. What are the feelings that you’re experiencing as the other person?",
    "Kongzi believes in the importance of filial piety. How do you show respect for your parents? (1.11)",
    "Kongzi encourages elaborate funerals and suggests one should mourn their parents for three years. How would you mourn the loss of a loved one?",
    "Your younger brother refuses to help your mother with washing dishes. How would you respond?",
    "What makes you joyous?",
    "What is one pattern or convention that you observe in society? How does it affect your daily life, and how could one attempt to break that pattern?",
    "Do you believe it is better to guide with virtue or to guide with punishments? (2.3)",
    "Suppose your parents want you to do something that you do not want to do. Despite your disagreement, would you still follow their lead? (4.18)",
    "How do you feel about the age of your parents? Do you think about it often? Does it cause you anxiety or joy? (4.21)",
  ],
  Mengzi: [
    "You’re walking to work, and you see a child about to fall into a well. How do you react? (2A6)",
    "Imagine your human nature as a sprout. Is it strong and upright or weak and limp? How would you nourish it? (2A6)",
    "How would you feel if the corpses of your parents were in a roadside ditch, being gnawed on by wild animals and maggots? (3A5)",
    "Think of a day when you were feeling low energy. What caused it and how did you deal with it?",
    "Mengzi believed that human nature is innately good. Can you think of an example that might show how human nature is good? (2A6)",
    "You are a farmer trying to encourage your seedlings to grow faster. Are you more likely to patiently water them or to pull them up in your haste? (2A2)",
    "You come across a barren field near a mountain. Was it barren in the first place, or caused by the environment, animals, and people around it? How might you relate this back to human nature? (6A8)",
    "Suppose you are in the shower, and a member of your family cries for help. Would you run out of the shower to help them? Does your answer change if the person asking for help were your neighbor and not your family member? (4B29)",
    "Mengzi argues that the ways in which people seek wealth, rank, profit, and success are often shameful. What do you think of this claim? (4B33)",
    "How do you interact, if at all, with people who you believe are not righteous or benevolent? (4A10)",
    "Mengzi argues that “In years of plenty, most young men are gentle; in years of poverty, most young men are cruel.” Do you agree? How do you think external factors affect one’s ability to self cultivate? (6A7)",
  ],
  Zhuangzi: [
    "Take a walk in the woods. Imagine you are a leaf on the tree. How does the sun feel? The wind?",
    "You’re reading this card. Are you truly awake and reading this card right now? Or are you dreaming that you are awake and reading this card? Or are you dreaming that you are dreaming that you are awake and reading this card?",
    "Imagine you are a bird. What would be your biggest weakness?",
    "Imagine you are a worm. What would be your biggest strength?",
    "When mourning the death of his wife, Zhuangzi beat his bathtub and sang. If one of your loved ones passed away, would you do the same?",
    "Find the closest object to you. Think about its connections to the world and how it’s connected to you.",
    "Describe a time when you acted according to your gut. Do you regret the decision you made?",
    "Do you believe language is complete? Why or why not?",
    "What societal divisions, if any, are meaningless? Which, if any, are meaningful?",
    "Do you understand life?",
    "Do you gravitate towards rational thinking or towards experience and intuition?",
  ],
  Dongzhongshu: [
    "Imagine you are riding in a trolley whose brakes are not working. You are headed towards a switch in the train tracks. If you continue on the current track, five people will be killed. You can pull a lever that would switch the trolley to another track, which would save the five people but kill another person who is standing on the tracks. Would you pull the lever?",
    "Suppose you have a limited budget. You can build a bridge for your neighborhood or invest that money into education. What would you choose, and how would you convince your superiors of your vision?",
    "Dong Zhongshu believes in creating an educational system focused on self-cultivation, where individuals are promoted based on the degree to which they are striving to cultivate themselves. Do you agree? What are your opinions on the role of education? ",
    "You are the leader of a developing country where water is limited: there is not enough water for all of your citizens. How do you determine who receives water and who does not? ",
    "Describe your experience with education. Do you believe your education served you well? ",
    "Do you prioritize fairness or efficiency? Why? ",
    "Suppose you are the leader of a small village. You are given a magical coin and offered the opportunity to flip it. If the coin lands on heads with probability X, everyone in your village will flourish. If the coin lands on tails, you and your subjects will die a painful death. What is the lowest value you would be willing to assign to X to choose to flip the coin?",
    "If you were an emperor or empress trying to construct a meritocracy, how would you identify merit in your subjects? Who deserves to be promoted?",
    "Reflect on your current role in society. How would you describe your current position? Do you think you occupy a fitting position, or do you think you should have a higher or lower role in society? Why?",
  ],
  Summary: [
    "How would you mourn the loss of a loved one? ",
    "What makes someone deserving of political power?",
    "Are human beings innately good or evil? ",
    "Is self-cultivation attainable? Why or why not?",
    "Would you sacrifice morality for power or prestige? ",
    "Who is the most moral person, deceased or alive, that you know? How do you know they are moral?",
    "You are the principal of a school. What texts would you incorporate in your school’s curriculum? ",
    "Which do you believe is more effective in changing human behavior: internal or external motivation? Why?",
    "To what extent do you believe that human nature is malleable? ",
    "What characteristics or traits would you like to develop in yourself? What would you like to reduce?",
  ],
};

export default Cards;
